In [1]:
import numpy as np
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [2]:
#to add new elements into the array
new_arr=np.append(arr,4.5)
new_arr

array([1. , 2. , 3. , 4. , 5. , 4.5])

In [7]:
#to add multiple values
new_arr=np.append(arr,[45,67,90])
new_arr

array([ 1,  2,  3,  4,  5, 45, 67, 90])

In [11]:
#to insert an element at particular position
new_arr=np.insert(arr,2,49)
new_arr

array([ 1,  2, 49,  3,  4,  5])

In [12]:
#to insert multiple values into array
new_arr=np.insert(arr,3,[12,13,14])
new_arr

array([ 1,  2,  3, 12, 13, 14,  4,  5])

In [13]:
#to delete an element from the array
new_arr1=np.delete(new_arr,np.where(new_arr==12))
new_arr1

array([ 1,  2,  3, 13, 14,  4,  5])

In [14]:
#to delete multiple values
new_arr1=np.setdiff1d(new_arr,[13,14])
new_arr1

array([ 1,  2,  3,  4,  5, 12])

In [15]:
#to delete an element based on index
new_arr1=np.delete(new_arr,2)
new_arr1

array([ 1,  2, 12, 13, 14,  4,  5])

In [16]:
#to delete multiple values based on index
new_arr1=np.delete(new_arr,[2,3])
new_arr1

array([ 1,  2, 13, 14,  4,  5])

In [17]:
#to display the elements which are less than 5
new_arr1<5

array([ True,  True, False, False,  True, False])

In [18]:
new_arr1[new_arr1<5]

array([1, 2, 4])

In [19]:
#to display the elements between two values
(new_arr1>3)&(new_arr1<12)

array([False, False, False, False,  True,  True])

In [20]:
new_arr1[(new_arr1>3)&(new_arr1<12)]

array([4, 5])

In [21]:
#to replace the values in the array
new_arr==23

array([False, False, False, False, False, False, False, False])

In [23]:
new_arr[new_arr==2]=156
new_arr

array([  1, 156,   3,  12,  13,  14,   4,   5])

In [24]:
#to create array full of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
#to create array full of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
#to create once with int data type
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
#task
#to create range of element as array
new_arr=np.arange(12)

In [30]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
#to convert 1d array to multidimensional array
new_arr1=new_arr.reshape(4,3)
new_arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
#to create array of identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#to find mean
np.mean(new_arr)

5.5

In [34]:
#to find median
np.median(new_arr)

5.5

In [35]:
#to find variance
np.var(new_arr)

11.916666666666666

In [36]:
#to find standard deviation
np.std(new_arr)

3.452052529534663

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])