In [8]:
#creating an array
import numpy as np
l=[1,2,3,4,5]
ar1=np.array(l)
ar1

array([1, 2, 3, 4, 5])

In [3]:
#to know the type of the elements of the array
ar1.dtype


dtype('int32')

In [9]:
#to convert into original form
ar1.tolist()

[1, 2, 3, 4, 5]

In [5]:
#to know the type of the string
t1="hello"
ar1=np.array(t1)
ar1.dtype

dtype('<U5')

In [10]:
#to multiply the elements in the array
ar1*2

array([ 2,  4,  6,  8, 10])

In [11]:
#to add new elements into the array
ar2=[1,2,3,4,5]
l=np.array(ar2)
new_arr=np.append(ar2,90)
new_arr

array([ 1,  2,  3,  4,  5, 90])

In [12]:
#to create range of elements as array
ar=np.arange(1,15)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
#to find the length of the array
len(ar)

14

In [14]:
#to convert 1d array to multidimensional array
ar2=np.arange(8)
ar3=ar2.reshape(2,4)
ar3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
#to perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
ar2.shape

(5, 5)

In [17]:
#to get particular no of rows and columns
ar2[0,3]

3

In [18]:
#ar2[row_start:row_end,col_start:col_end,step]
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [19]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [20]:
#using negative index
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#using negative index
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [27]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [30]:
#negative indexing of task1
ar3[-3:-1,-3:-1]

array([[27, 28],
       [37, 38]])

In [28]:
#tasks
#positive indexing of task1
ar3[2:4,7:9]

array([[27, 28],
       [37, 38]])

In [38]:
#print 34,35,44,45
#using positive index
ar3[3:,4:6]

array([[34, 35],
       [44, 45]])

In [39]:
#using negative index
ar3[-2:,-6:-4]

array([[34, 35],
       [44, 45]])

In [44]:
#print 18,19
#using positive index
ar3[1:2,8:]

array([[18, 19]])

In [47]:
#using negative index
ar3[-4:-3,-2:]

array([[18, 19]])

In [50]:
#print 30,31,40,41
#using positive index
ar3[3:,0:2]

array([[30, 31],
       [40, 41]])

In [51]:
#using negative index
ar3[-2:,-10:-8]

array([[30, 31],
       [40, 41]])

In [34]:
#adding the elemeents of the array
np.sum(ar3,axis=0)#to add the elements based on columns

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [35]:
np.sum(ar3,axis=1)#to add the elements based on rows

array([ 45, 145, 245, 345, 445])

In [36]:
np.sum(ar3)

1225

In [40]:
#linspace
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [41]:
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [43]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [45]:
np.random.randint(20,30)

22

In [49]:
#uniform distribution
np.random.rand(4)

array([0.0276335 , 0.05655115, 0.96661435, 0.05065469])

In [53]:
#normalised distribution
np.random.randn(5)

array([ 1.59769899,  0.18742092,  0.95604101,  0.69943221, -0.06319374])

In [54]:
ar3.min()

0

In [55]:
ar3.max()

49

In [56]:
ar3.tolist()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]

In [59]:
#to find the index of minimum value
ar3.argmin()

0

In [60]:
ar3.argmax()

49

In [62]:
l1=[12,1,3,15,19]
np1=np.array(l1)
print(np1.argmin())
print(np1.argmax())

1
4


In [63]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.63585993,  1.55740772, -0.14254654, -0.8559934 ,  0.15158947])

In [64]:
1/np.sin(np1)

array([-1.8636796 ,  1.18839511,  7.0861674 ,  1.53778056,  6.67212849])

In [65]:
np.cos(np1)/np.sin(np1)

array([-1.57267341,  0.64209262, -7.01525255, -1.16823331,  6.59676425])

In [81]:
#task
#write python code for the below logic
np2=np.array([1,2,3,8,7])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for i in range(diff):
        np3=np.append(np3, 1)

np.sum(np2*np3)

47

In [82]:
np1=np.array([1,2,3,78,np.nan,np.nan])

In [83]:
np1[np.isnan(np1)]

array([nan, nan])

In [84]:
np1[~np.isnan(np1)]

array([ 1.,  2.,  3., 78.])

In [86]:
#pandas
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [87]:
type(pd.Series(my_data))

pandas.core.series.Series

In [88]:
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [89]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [91]:
pd.Series(data=[print,len,sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [93]:
class profile:
    @
    def display(self):
        print("hi")
p=profile()
p.display()

hi


In [99]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner


@decor
def greet():
    return "good afternoon"
print(greet())

GOOD AFTERNOON


In [100]:
sr1=pd.Series([1,2,3,4,5],['USA',"India","Canada",'UK',"Egypt"])
sr1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

In [102]:
sr1['USA']

1

In [103]:
#acces values using indexing
sr1[0:3]

USA       1
India     2
Canada    3
dtype: int64

In [106]:
ser2=pd.Series([5,6,7,8],['USA','brazil','Canada','UK'])

In [107]:
sr1+ser2

Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
brazil     NaN
dtype: float64

In [108]:
#To create a new data in series
ser2

USA       5
brazil    6
Canada    7
UK        8
dtype: int64

In [109]:
ser2['china']="duplicate"

In [110]:
ser2

USA               5
brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [111]:
#to delete particular record
ser2.drop('USA')

brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [112]:
#Data Frame
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.027325  0.128952  0.516530 -0.751677
1  0.689405  0.444742  0.824047 -1.722238
2 -0.315322  0.519244  0.875383  0.686486
3  0.251763 -2.331336 -0.620561  0.754120
4 -0.540013  1.183003  1.176133 -1.282029

In [117]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -0.611056 -0.321243  1.586325  0.357791
B  1.714838 -0.092493 -0.133662  1.019263
C  0.500050 -0.490418  0.269012 -0.374209
D -0.112451  0.827754  1.103370  1.591874
E  1.075003  3.025061  0.584892 -1.091423

In [114]:
#to convert dictionary to DataFrame
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [115]:
df=pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [116]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [118]:
df

W         X         Y         Z
A -0.611056 -0.321243  1.586325  0.357791
B  1.714838 -0.092493 -0.133662  1.019263
C  0.500050 -0.490418  0.269012 -0.374209
D -0.112451  0.827754  1.103370  1.591874
E  1.075003  3.025061  0.584892 -1.091423

In [119]:
df.T

A         B         C         D         E
W -0.611056  1.714838  0.500050 -0.112451  1.075003
X -0.321243 -0.092493 -0.490418  0.827754  3.025061
Y  1.586325 -0.133662  0.269012  1.103370  0.584892
Z  0.357791  1.019263 -0.374209  1.591874 -1.091423

In [120]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [121]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [122]:
type(df)

pandas.core.frame.DataFrame

In [123]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [125]:
df.values

array([[-0.6110558 , -0.32124274,  1.58632527,  0.35779063],
       [ 1.71483838, -0.09249318, -0.13366164,  1.01926266],
       [ 0.50005049, -0.49041839,  0.26901185, -0.37420899],
       [-0.1124513 ,  0.82775351,  1.10337044,  1.59187363],
       [ 1.07500288,  3.02506053,  0.58489179, -1.09142287]])

In [126]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [127]:
df.ndim

2

In [128]:
df.size

20

In [129]:
#to access specific cloumns 
df["W"]

A   -0.611056
B    1.714838
C    0.500050
D   -0.112451
E    1.075003
Name: W, dtype: float64

In [131]:
type(df["W"])

pandas.core.series.Series

In [132]:
#to access multiple columns
df[['W','X','Z']]

W         X         Z
A -0.611056 -0.321243  0.357791
B  1.714838 -0.092493  1.019263
C  0.500050 -0.490418 -0.374209
D -0.112451  0.827754  1.591874
E  1.075003  3.025061 -1.091423

In [134]:
#to create new column
df['new']=df['W']+df['Y']
df

W         X         Y         Z       new
A -0.611056 -0.321243  1.586325  0.357791  0.975269
B  1.714838 -0.092493 -0.133662  1.019263  1.581177
C  0.500050 -0.490418  0.269012 -0.374209  0.769062
D -0.112451  0.827754  1.103370  1.591874  0.990919
E  1.075003  3.025061  0.584892 -1.091423  1.659895

In [137]:
df.drop('new',axis=1)

W         X         Y         Z
A -0.611056 -0.321243  1.586325  0.357791
B  1.714838 -0.092493 -0.133662  1.019263
C  0.500050 -0.490418  0.269012 -0.374209
D -0.112451  0.827754  1.103370  1.591874
E  1.075003  3.025061  0.584892 -1.091423

In [138]:
df.drop('new',axis=1,inplace=True)
df

W         X         Y         Z
A -0.611056 -0.321243  1.586325  0.357791
B  1.714838 -0.092493 -0.133662  1.019263
C  0.500050 -0.490418  0.269012 -0.374209
D -0.112451  0.827754  1.103370  1.591874
E  1.075003  3.025061  0.584892 -1.091423

In [3]:
#tasks
#adding new array
import numpy as np
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
new_arr=np.append(ini_array,[12,23,45])
new_arr

array([ 1,  2,  3, 45,  4,  7,  9,  6, 10, 12, 23, 45])

In [5]:
#frequency of all the elements in the series
import pandas as pd
se = pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])
se.value_counts()

2    4
1    3
3    3
4    2
5    1
Name: count, dtype: int64

In [7]:
#reshape the series into dataframe
ser = pd.Series(np.random.randint(1, 10, 35))
pd.DataFrame(ser)

0
0   4
1   8
2   9
3   7
4   5
5   2
6   6
7   5
8   9
9   2
10  4
11  2
12  4
13  1
14  2
15  3
16  7
17  7
18  5
19  2
20  9
21  8
22  7
23  8
24  7
25  1
26  3
27  1
28  5
29  1
30  9
31  2
32  4
33  8
34  8

In [9]:
# to Find the positions of numbers that are multiples of 3 from ser
ser = pd.Series(np.random.randint(1, 10, 10))
res=np.argwhere(ser%3==0)
res

array([[2]], dtype=int64)

In [11]:
#to Join the two series
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
ser=pd.DataFrame(ser1,ser2)
ser

0
a NaN
b NaN
c NaN
d NaN
e NaN

In [16]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [17]:
df[['name','score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0